#
#   Main playbook to deploy all the Wall-AI ITER infrastructure in TeideHPC IaaS
#

- hosts: iaas
  vars:
    ansible_connection: local
    iaas_info: "{{ lookup('ansible.builtin.ini', 'IAAS type=properties file=' +
      ENV_FILE) | split(' ') }}"
    domain: "{{ iaas_info.1 | regex_replace('\"', '') }}"
  vars_files:
  - env_vars/vault.yaml
  gather_facts: true
  roles:
  - role: iter_iaas

- hosts: iaas
  gather_facts: false
  remote_user: "{{ def_user }}"
  roles:
  - role: mgmt_user

- import_playbook: "site_common.yaml"
  when: inventory_hostname in groups['iaas']
