#
#   Main playbook to deploy all the Wall-AI ITER infrastructure
#


- hosts: masters, workers
  gather_facts: true
  roles:
  - role: base

# - hosts: masters, workers
#   gather_facts: false
#   roles:
#   - role: k8s_cluster
# 
# - hosts: workers
#   gather_facts: false
#   roles:
#   - role: k8s_kafka
# 
# - hosts: workers
#   gather_facts: false
#   roles:
#   - role: k8s_mongodb
# 
# - hosts: workers
#   gather_facts: false
#   roles:
#   - role: k8s_apps
# 
