#
#   Management user creation (to be included into other role plays)
#
# Target hosts: inherited from the parent role
# Vars: none
#

- name: Check availability of VM's
  become: true
  ansible.builtin.copy:
    content: "  VM created and operated by EAVE.\n"
    dest: "/etc/motd"

- name: Create ansible user
  become: true
  ansible.builtin.user:
    name: "ansible"
    umask: "002"
    append: true
    groups: "wheel"
    ssh_key_type: "ssh-ed25519"
    generate_ssh_key: true

- name: Set management user passwordless
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/sudoers"
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

# - name: Get ansible user public key from management server
#   delegate_to: localhost
#   ansible.builtin.set_fact:
#     local_pk: "{{ ansible_ssh_host_key_ed25519_public_keytype }} {{ ansible_ssh_host_key_ed25519_public }} {{ ansible_user_id }}@{{ ansible_hostname }}"
#
# - name: Set up authorized_keys file on every managed node
#   become: true
#   ansible.builtin.copy:
#     owner: "{{ ansible_user_id }}"
#     group: "{{ ansible_user_id }}"
#     mode: "600"
#     content: "{{ local_pk }}"
#     dest: "{{ ansible_user_dir }}/.ssh/authorized_keys"

- name: Set up authorized_keys file on every managed node
  become: true
  ansible.builtin.copy:
    owner: "ansible"
    group: "ansible"
    mode: "600"
    remote_src: false
    src: "/home/ansible/.ssh/id_ed25519.pub"
    dest: "/home/ansible/.ssh/authorized_keys"

