#
#   Kubernetes cluster deployment
#
# Target hosts: master, worker
#

- name: Disabling swap on every node
  block:
  - name: Disable swap permanently
    with_items:
    - swap
    - none
    ansible.posix.mount:
      path: "{{ item }}"
      fstype: swap
      state: absent

  - name: Disable swap right now
    when: ansible_swaptotal_mb > 0
    ansible.builtin.command: swapoff -a

- name: Remove old packages versions
  ansible.builtin.dnf:
    state: absent
    name:
    - docker
    - docker-ce
    - docker-ce-cli
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine
    - podman
    - runc
    - containerd.io
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni

- name: Including and enabling Docker repo by commands
  block:
  - name: Include Docker repo
    ansible.builtin.command: dnf config-manager --add-repo
      https://download.docker.com/linux/centos/docker-ce.repo

  - name: Enable Docker repo
    ansible.builtin.command: dnf config-manager --enable docker-ce-stable

- name: Include Kubernetes repo
  ansible.builtin.yum_repository:
    name: "kubernetes"
    description: "Kubernetes stable v1.31"
    baseurl: "https://pkgs.k8s.io/core:/stable:/v1.31/rpm/"
    enabled: true
    gpgcheck: true
    gpgkey: "https://pkgs.k8s.io/core:/stable:/v1.31/rpm/repodata/repomd.xml.key"
    # exclude: ["kubelet", "kubeadm", "kubectl", "tools", "kubernetes-cni"]
    state: present

- name: Update all OS packages
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: true

- name: Install cluster services
  ansible.builtin.dnf:
    state: latest
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - kubelet
    - kubeadm
    - kubectl

- name: DNF autoremove
  ansible.builtin.dnf:
    autoremove: true

